#ifndef CONFIG_H
#define CONFIG_H

#define MEM_SIZE 1000
#define FRAME_STORE_SIZE 900
#define MAX_LINE_LENGTH 100
#define MAX_PROGRAM 100
#define MAX_BACKGROUND_NAME_LENGTH 32
#define FRAME_SIZE 3
#endif